document.writeln("<footer class=\"ui stackable\" id=\"footer\">");
document.writeln("    <nav class=\"ui five column stackable grid container footer-nav\">");
document.writeln("      <div class=\"column footer-nav-cont\">");
document.writeln("        <h6>选购及了解</h6>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"#\">iPad</a></li>");
document.writeln("          <li><a href=\"#\">iPhone</a></li>");
document.writeln("          <li><a href=\"#\">Watch</a></li>");
document.writeln("          <li><a href=\"#\">Watch</a></li>");
document.writeln("          <li><a href=\"#\">Music</a></li>");
document.writeln("          <li><a href=\"#\">iTunes</a></li>");
document.writeln("          <li><a href=\"#\">iPod touch</a></li>");
document.writeln("          <li><a href=\"#\">配件</a></li>");
document.writeln("          <li><a href=\"#\">App Store 充值卡</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"column footer-nav-cont\">");
document.writeln("        <h6>Apple Store 商店</h6>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"#\">查找零售店</a></li>");
document.writeln("          <li><a href=\"#\">Genius Bar 天才吧</a></li>");
document.writeln("          <li><a href=\"#\">Today at Apple</a></li>");
document.writeln("          <li><a href=\"#\">Apple 夏令营</a></li>");
document.writeln("          <li><a href=\"#\">Field Trip 课外活动</a></li>");
document.writeln("          <li><a href=\"#\">Apple Store App</a></li>");
document.writeln("          <li><a href=\"#\">翻新和优惠</a></li>");
document.writeln("          <li><a href=\"#\">分期付款</a></li>");
document.writeln("          <li><a href=\"#\">重复使用和循环利用</a></li>");
document.writeln("          <li><a href=\"#\">订单状态</a></li>");
document.writeln("          <li><a href=\"#\">选购帮助</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"column footer-nav-cont\">");
document.writeln("        <h6>教育应用</h6>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"#\">Apple 与教育</a></li>");
document.writeln("          <li><a href=\"#\">高校师生选购</a></li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"tablet-computer-only\">");
document.writeln("          <h6>商务应用</h6>");
document.writeln("          <ul>");
document.writeln("            <li><a href=\"#\">Apple 与商务</a></li>");
document.writeln("            <li><a href=\"#\">商务选购</a></li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <!-- 移动端显示 -->");
document.writeln("      <div class=\"column footer-nav-cont mobile-only\" style=\"display: none;\">");
document.writeln("        <h6>商务应用</h6>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"#\">Apple 与商务</a></li>");
document.writeln("          <li><a href=\"#\">商务选购</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("");
document.writeln("      <div class=\"column footer-nav-cont\">");
document.writeln("        <h6>账户</h6>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"#\">管理你的 Apple ID</a></li>");
document.writeln("          <li><a href=\"#\">Apple Store 账户</a></li>");
document.writeln("          <li><a href=\"#\">iCloud.com</a></li>");
document.writeln("          <li><a href=\"#\"></a></li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"tablet-computer-only\">");
document.writeln("          <h6>Apple 价值观</h6>");
document.writeln("          <ul>");
document.writeln("            <li><a href=\"#\">辅助功能</a></li>");
document.writeln("            <li><a href=\"#\">环境责任</a></li>");
document.writeln("            <li><a href=\"#\">隐私</a></li>");
document.writeln("            <li><a href=\"#\">供应商责任</a></li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <!-- 移动端显示 -->");
document.writeln("      <div class=\"column footer-nav-cont mobile-only\" style=\"display: none;\">");
document.writeln("          <h6>Apple 价值观</h6>");
document.writeln("          <ul>");
document.writeln("            <li><a href=\"#\">辅助功能</a></li>");
document.writeln("            <li><a href=\"#\">环境责任</a></li>");
document.writeln("            <li><a href=\"#\">隐私</a></li>");
document.writeln("            <li><a href=\"#\">供应商责任</a></li>");
document.writeln("          </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"column footer-nav-cont\">");
document.writeln("        <h6>关于 Apple</h6>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"#\">Newsroom</a></li>");
document.writeln("          <li><a href=\"#\">Apple 管理层</a></li>");
document.writeln("          <li><a href=\"#\">工作机会</a></li>");
document.writeln("          <li><a href=\"#\">活动</a></li>");
document.writeln("          <li><a href=\"#\">联系 Apple</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </nav>");
document.writeln("    <div class=\"ui container footer-bottom\">");
document.writeln("      <p>更多选购方式：前往 <a>Apple Store 零售店</a>，致电 400-666-8800 或查找在你附近的 <a>授权经销商</a>。</p>");
document.writeln("      <i class=\"ui divider container\"></i>");
document.writeln("      <div class=\"row copyright\">");
document.writeln("        <p class=\"copyright-p\">Copyright © 2018 Apple Inc. 保留所有权利。</p>");
document.writeln("        <ul class=\"copyright-cont\">");
document.writeln("          <li><a href=\"#\">隐私政策</a></li>");
document.writeln("          <li><a href=\"#\">使用条款</a></li>");
document.writeln("          <li><a href=\"#\">销售政策</a></li>");
document.writeln("          <li><a href=\"#\">法律信息</a></li>");
document.writeln("          <li><a href=\"#\">网站地图</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");