document.writeln("<div class=\"ui grid mobile only\">");
document.writeln("    <nav class=\"ui fixed fitted inverted borderless three item menu\">");
document.writeln("      <div class=\"ui container mobile-nav\">");
document.writeln("        <div class=\"item\">");
document.writeln("          <a href=\"#\" class=\"ui left aligned item show-nav-cli\">");
document.writeln("            <i class=\"icon content\"></i>");
document.writeln("          </a>");
document.writeln("        </div>");
document.writeln("        <div class=\"item\">");
document.writeln("          <a href=\"index.html\" class=\"item\">");
document.writeln("            <i class=\"apple icon\"></i>");
document.writeln("          </a>");
document.writeln("        </div>");
document.writeln("        <div class=\"item\">");
document.writeln("          <a href=\"#\" class=\"ui right aligned item\">");
document.writeln("            <i class=\"icon unlock alternate\"></i>");
document.writeln("          </a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </nav>");
document.writeln("    <ul class=\"mobile-show-nav\">");
document.writeln("      <li><a href=\"mac.html\" class=\"item\">Mac</a></li>");
document.writeln("      <li><a href=\"#\" class=\"item\">iPad</a></li>");
document.writeln("      <li><a href=\"#\" class=\"item\">iPhone</a></li>");
document.writeln("      <li><a href=\"#\" class=\"item\">Watch</a></li>");
document.writeln("      <li><a href=\"#\" class=\"item\">Music</a></li>");
document.writeln("      <li><a href=\"#\" class=\"item\">技术支持</a></li>");
document.writeln("      <li>");
document.writeln("        <div class=\"ui inverted left icon input\">");
document.writeln("          <input type=\"text\" placeholder=\"搜索...\">");
document.writeln("          <i class=\"search icon\"></i>");
document.writeln("        </div>");
document.writeln("      </li>");
document.writeln("    </ul>");
document.writeln("  </div>");
document.writeln("  <nav class=\"ui grid fixed fitted inverted borderless nine item menu tablet computer only\">");
document.writeln("    <div class=\"ui container\">");
document.writeln("      <a href=\"index.html\" class=\"item\">");
document.writeln("        <i class=\"apple icon\"></i>");
document.writeln("      </a>");
document.writeln("      <a href=\"mac.html\" class=\"item\">Mac</a>");
document.writeln("      <a href=\"#\" class=\"item\">iPad</a>");
document.writeln("      <a href=\"#\" class=\"item\">iPhone</a>");
document.writeln("      <a href=\"#\" class=\"item\">Watch</a>");
document.writeln("      <a href=\"#\" class=\"item\">Music</a>");
document.writeln("      <a href=\"#\" class=\"item\">技术支持</a>");
document.writeln("      <a href=\"#\" class=\"item\">");
document.writeln("        <i class=\"icon search\"></i>");
document.writeln("      </a>");
document.writeln("      <a href=\"#\" class=\"item\">");
document.writeln("        <i class=\"icon unlock alternate\"></i>");
document.writeln("      </a>");
document.writeln("    </div>");
document.writeln("  </nav>");